### ISSUE TITLE
Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.

### ISSUE THREAD

**Issue by dlenskyi** [exponentjs/react-native-read-more#39]
I'm getting warning
 ```
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
at node_modules/react/cjs/react.development.js:471:2 in Component.prototype.setState
at node_modules/react-native-read-more-text/index.js:11:2 in ReadMore#componentDidMount
at [native code]:null in flushedQueue
at [native code]:null in invokeCallbackAndReturnFlushedQueue
```
Anyone can help me with that please?

**Comment by Randall71** [comment]
This is not an issue with this library but with your state update in your application. to fix this check https://www.debuggr.io/react-update-unmounted-component/
